stages:
  get_data:
    cmd: python download_data.py
    deps:
    - download_data.py
    outs:
    - data_raw.csv
  process:
    cmd: python preprocess.py
    deps:
    - preprocess.py
    - data_raw.csv
    outs:
    - data_processed.csv
  train:
    cmd: python train.py
    deps:
    - train.py
    - data_processed.csv
    outs:
    - by_region.png
    metrics:
    - metrics.json:
        cache: false
